### ISSUE TITLE
USB Port Latency Timer

### ISSUE THREAD

**Issue by ligerfotis** [iyeszin/hri_sl_ros2#1]
/sys/bus/usb-serial/devices/ttyUSB0/latency_timer does not correspond to a file in my computer. Can you please fix it?

**Comment by iyeszin** [comment]
You need to run the following script:
`sudo apt install dbus-x11`

The dbus-launch command is used to start a session bus instance of dbus-daemon from a shell script.``

**Comment by ligerfotis** [comment]
(base) fotis@fotis-AORUS-15P-YD:~/PycharmProjects/hri_sl_ros2$ ros2 launch rh8d_ros2 rh8d_col.launch.py
Package 'rh8d_ros2' not found: "package 'rh8d_ros2' not found, searching: ['/opt/ros/humble']"

**Comment by ligerfotis** [comment]
base) fotis@fotis-AORUS-15P-YD:~/PycharmProjects/hri_sl_ros2$ ros2 launch rh8d_hw rh8d_hw_combined.launch.py
[INFO] [launch]: All log files can be found below /home/fotis/.ros/log/2023-10-13-16-15-47-793274-fotis-AORUS-15P-YD-81248
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rh8d_tactile_combined-1]: process started with pid [81250]
[rh8d_tactile_combined-1] [INFO] [1697206548.049167178] [rh8d_tactile]: Light mode is: False
[rh8d_tactile_combined-1] [INFO] [1697206548.049520082] [rh8d_tactile]: Hand polarity is : L_
[rh8d_tactile_combined-1] [INFO] [1697206548.049823301] [rh8d_tactile]: Baudrate is : 1000000
[rh8d_tactile_combined-1] [INFO] [1697206548.050438540] [rh8d_tactile]: Baudrate is : 1000000
[rh8d_tactile_combined-1] [INFO] [1697206548.050953948] [rh8d_tactile]: Hand port name is: /dev/ttyUSB0
[rh8d_tactile_combined-1] [INFO] [1697206548.051451342] [rh8d_tactile]: Sensor port name is: /dev/ttyUSB1
[rh8d_tactile_combined-1] [INFO] [1697206548.051935577] [rh8d_tactile]: Frequency is: 50
[rh8d_tactile_combined-1] [INFO] [1697206548.052404579] [rh8d_tactile]: Sensor number is : 5
[rh8d_tactile_combined-1] [INFO] [1697206548.052882719] [rh8d_tactile]: Joint mapping imported, main board mapping is: 40
[rh8d_tactile_combined-1] [ERROR] [1697206548.053523885] [rh8d_tactile]: Could not open serial port /dev/ttyUSB1
[INFO] [rh8d_tactile_combined-1]: process has finished cleanly [pid 81250]

**Comment by iyeszin** [comment]
If you have trouble with permissions on serial port (for example if you cannot open a serial port on GTKTerm), you can solve this issue by adding yourself to the dialout group. To do so, open a terminal and type :

sudo usermod -a -G dialout $USER

Then logout and log back for the changes to take effect.

Kindly refer to https://github.com/seedrobotics/ros_robothands for more information.
